/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdditionalAnalysisImages: typeof import('./src/components/ResultPage/AdditionalAnalysisImages.vue')['default']
    BreadcrumbNav: typeof import('./src/components/common/BreadcrumbNav.vue')['default']
    DataGroupingCard: typeof import('./src/components/MainPage/DataGroupingCard.vue')['default']
    DataScatterChart: typeof import('./src/components/ResultPage/charts/DataScatterChart.vue')['default']
    HeatmapChart: typeof import('./src/components/ResultPage/charts/HeatmapChart.vue')['default']
    HistogramChart: typeof import('./src/components/ResultPage/charts/HistogramChart.vue')['default']
    InformationDetails: typeof import('./src/components/ResultPage/InformationDetails.vue')['default']
    KeyOrderingSettings: typeof import('./src/components/Settings/KeyOrderingSettings.vue')['default']
    LoadingDialog: typeof import('./src/components/common/LoadingDialog.vue')['default']
    MeasurementInfo: typeof import('./src/components/ResultPage/MeasurementInfo.vue')['default']
    MeasurementPoints: typeof import('./src/components/ResultPage/MeasurementPoints.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedGroupsCard: typeof import('./src/components/MainPage/SavedGroupsCard.vue')['default']
    ScatterDataSelector: typeof import('./src/components/ResultPage/charts/ScatterDataSelector.vue')['default']
    SearchSection: typeof import('./src/components/MainPage/SearchSection.vue')['default']
    SimplifiedMeasurementCard: typeof import('./src/components/DataTrend/SimplifiedMeasurementCard.vue')['default']
    StatisticalInfoByPoints: typeof import('./src/components/ResultPage/StatisticalInfoByPoints.vue')['default']
    StatisticalScatterChart: typeof import('./src/components/ResultPage/charts/StatisticalScatterChart.vue')['default']
    SummaryStatisticsBySites: typeof import('./src/components/ResultPage/SummaryStatisticsBySites.vue')['default']
    TimeSeriesChart: typeof import('./src/components/DataTrend/charts/TimeSeriesChart.vue')['default']
    ViewHistoryCard: typeof import('./src/components/MainPage/ViewHistoryCard.vue')['default']
  }
}
