"""Stable live_alarm data seam with mock/office adapters.

Do not edit this file when wiring the office: it dispatches, nothing more.
"""

from collections.abc import Sequence

from backend._runtime.data_provider import get_data_provider
from backend.ebeam._tool_specs import ToolType
from backend.ebeam.live_alarm.contracts import LiveAlarmPayload
from backend.ebeam.live_alarm.providers import mock as mock_provider


__all__ = ["get_board"]


def _provider():
    if get_data_provider("live_alarm") == "office":
        from backend.ebeam.live_alarm.providers import office
        return office
    return mock_provider


def get_board(tool_type: ToolType, fab_names: Sequence[str]) -> LiveAlarmPayload:
    return _provider().get_board(tool_type, fab_names)
